name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install root dependencies
      run: npm install

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend

    - name: Run frontend linting
      run: npm run lint
      working-directory: ./frontend

    - name: Run frontend build
      run: npm run build
      working-directory: ./frontend

    - name: Install backend dependencies
      run: npm install
      working-directory: ./backend

    - name: Run backend build
      run: npm run build
      working-directory: ./backend
